/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import cli.ComandLineInterface;
import manager.BatchService;
import manager.PreparationComponentManager;
import manager.PreparationManager;
import manager.SolutionManager;

public class App {
    public static void main(String[] args) {
        SolutionManager solutionManager= new SolutionManager();
        PreparationManager preparationManager= new PreparationManager();
        BatchService batchService= new BatchService();
        PreparationComponentManager preparationComponentManager= new PreparationComponentManager(preparationManager,batchService);
        ComandLineInterface cli = new ComandLineInterface(preparationManager, preparationComponentManager,solutionManager);
        cli.start();
    }
}